# --- env tests ---

cel_cc_test(
  env_config_test
  SRCS
    env/config_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_env_runtime_test
  SRCS
    env/env_runtime_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_env_std_extensions_test
  SRCS
    env/env_std_extensions_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_env_test
  SRCS
    env/env_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_env_yaml_test
  SRCS
    env/env_yaml_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_internal_ext_registry_test
  SRCS
    env/internal/ext_registry_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_internal_runtime_ext_registry_test
  SRCS
    env/internal/runtime_ext_registry_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_runtime_std_extensions_test
  SRCS
    env/runtime_std_extensions_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
cel_cc_test(
  env_type_info_test
  SRCS
    env/type_info_test.cc
  DEPS
    cel_common
    cel_runtime
    cel_checker
    cel_parser
    cel_extensions
    cel_compiler
    cel_validator
    cel_env
    cel_tools
    cel_testutil
    cel_checker_internal_testing
    cel_internal_testing
)
